#!/bin/bash
application_names="apache, mysql and redish revices"
start="start"
stop="stop"
if [ "$1" = "${start}" ]; then
  systemctl start mysql.service
  systemctl start apache2.service
  systemctl start redis.service
  echo " ${application_names} have been started"
fi

if [ "$1" = "${stop}" ]; then
  systemctl stop mysql.service
  systemctl stop apache2.service
  systemctl stop redis.service
  echo " ${application_names} have been stopped"
fi
